### ISSUE TITLE
How to do if I wnat to input a new emotions, like anxiety?

### ISSUE THREAD

**Issue by Leotanlio** [NetFACS/NetFACS#2]
As the title,
If I want to know the AU in the other emotion, how should I do?

**Comment by avrincon** [comment]
Hi,

If you would like to analyze AUs in a different emotion, then you will have to collect your own data (or find an existing dataset) with the emotion that you are interested in. 

However, the issues page is primarily to discuss bugs or new features, rather than how to use the package. For that you can refer to the tutorial.
